name: Deploy Frontend

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Log in to Docker
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t cygnetops/react-test -f Dockerfile.dev .

      - name: Run Tests
        run: docker run -e CI=true cygnetops/react-test npm test
        # ⚠️ Ensure your test files import `act` from 'react' instead of 'react-dom/test-utils'

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: docker-gh
          environment_name: Dockergh-env 
          existing_bucket_name: elasticbeanstalk-us-east-1-227113222475
          region: us-east-1
          version_label: ${{ github.sha }}-${{ github.run_id }}  # ← ensures unique version label
          deployment_package: deploy.zip
